### ISSUE TITLE
From where do you get the with function ?

### ISSUE THREAD

**Issue by mfrachet** [toddmotto/interpolate#10]
Hi,

I m trying to learn a bit more javascript code. I hope you can pass this issue as a question, and maybe answer it.

In fact, in your interpolate function body, you have a declaration of a with function that has to be evaluated internally  :

`function interpolate(tmpl) {
  var code = 'with(obj){return \'' +  tmpl.replace(getDelimiters, '\'+($1)+\'') + '\';}';
  return new Function('obj', code);
};`

Actually, where do you get this ? What does it refer to ?

Can you explain what's happening on here ?

**Comment by toddmotto** [comment]
Hey! Check this out, `with()` is actually pure JS :) http://stackoverflow.com/questions/1293798/javascript-with-function
