### ISSUE TITLE
Improved performance and code size

### ISSUE THREAD

**Issue by FWeinb** [toddmotto/interpolate#8]
I experimented with code generation and came to this result: http://jsfiddle.net/D3eaQ/2/

I compile the `tmpl` string down to javascript and than uses the `new Function()` constructor to generate a dynamic function. This implements everything that `interpolate.js` does plus it adds the ability to have minimal logic in the template like:

``` js
var tmpl='You are {{ age > 10 ? "old" : "young" }}';
```

It is also nearly 10x times faster than the current implementation: http://jsperf.com/perfinterpolate-vs-meta-programming

I am unsure if this is the goal of interpolate so I only create an issue for now.

**Comment by toddmotto** [comment]
This is awesome! If it works, passes the tests then PR it man ! :)

**Comment by FWeinb** [comment]
See PR #9 closing
